// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WheelOfFortune.Models;

namespace WheelOfFortune.Migrations.WheelOfFortune
{
    [DbContext(typeof(WheelOfFortuneContext))]
    [Migration("20171115210916_wheel_Creation")]
    partial class wheel_Creation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WheelOfFortune.Models.AdminCoupon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Status");

                    b.Property<int>("Value");

                    b.HasKey("ID");

                    b.ToTable("AdminCoupon");
                });

            modelBuilder.Entity("WheelOfFortune.Models.Wheels.Wheel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AllWheelSlices");

                    b.Property<bool>("IsWheelActive");

                    b.Property<string>("WheelDescription");

                    b.HasKey("Id");

                    b.ToTable("AdminWheels");
                });
#pragma warning restore 612, 618
        }
    }
}
